config/routes.rb
Rails.application.routes.draw do
  resources :questions

  resources :questions do
    resources :answers, only: [:create, :update]
  end

  get '/auth/github/callback', to: 'sessions#create'

  resources :sessions, only: [:destroy]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions
  has_many :answers

  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_by(provider: provider, uid: uid) || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)

    create(
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      username: auth.info.nickname,
      avatar_url: auth.info.image
    )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  MIN_ANSWER_LENGTH = 10

  def update
    @question = Question.find(params[:question_id])

    if @question.uid != current_user.id
      redirect_to '/questions'
    end

    @current_favorite = Answer.where(question_id: params[:question_id]).where(is_favorite: true)
    if !@current_favorite.empty?
      @current_favorite[0].is_favorite = false
      @current_favorite[0].save
    end
    @answer = Answer.find(params[:id])
    @answer.is_favorite = true
    @answer.save

    redirect_to question_path(@question)
  end



  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.uid = session[:user_id]
    @answer.question = @question

    if answer_params["description"].length < MIN_ANSWER_LENGTH
      flash[:notice] = "Please supply a longer answer"
      redirect_to question_path(@question)
    elsif @answer.save
      redirect_to question_path(@question)
    else
      flash.now[:notice] = "Sorry! Save failed...."
      render :new
    end
  end

  private

  def answer_params
    # this method will return a hash like this:
    # { title: "whatever title", author: "some person", body: "blah blah blah" }
    params.require(:answer).permit(:description, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find(user_id) if user_id.present?
  end

  def signed_in?
    current_user.present?
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end

  def current_favorite
  end

  protect_from_forgery with: :exception

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  MIN_TITLE_LENGTH = 4
  MIN_DESCRIPTION_LENGTH = 15

  def index
    @questions = Question.all.order("updated_at desc")
  end

  def show
    @question = Question.find(params["id"])
    @new_answer = Answer.new
    @answers = Answer.where(question_id: params["id"]).order("is_favorite desc, updated_at desc")
    @creator = @question.uid

  end

  def edit
    @question = Question.find(params["id"])
  end

  def update

    @question = Question.find(params["id"])

    if @question.uid != current_user.id
      redirect_to '/questions'
    end

    if question_params[:title].length < MIN_TITLE_LENGTH
      flash.now[:notice] = "Please supply a longer title"
      render :new
      return
    elsif question_params[:description].length < MIN_DESCRIPTION_LENGTH
      flash.now[:notice] = "Please supply a longer description"
      render :new
      return
    elsif @question.update(question_params)
      redirect_to '/questions'
    else
      flash.now[:notice] = "Sorry! Save failed...."
      render :new
    end
  end

  def create

    @question = Question.new(question_params)
    @question.uid = session[:user_id]

    if question_params[:title].length < MIN_TITLE_LENGTH
      flash.now[:notice] = "Please supply a longer title"
      render :new
      return
    elsif question_params[:description].length < MIN_DESCRIPTION_LENGTH
      flash.now[:notice] = "Please supply a longer description"
      render :new
      return
    elsif @question.save
      redirect_to '/questions'
    else
      flash.now[:notice] = "Sorry! Save failed...."
      render :new
    end

  end

  def new
    @question = Question.new
  end


  def destroy
    @question = Question.find(params[:id])
    @question.answers.destroy_all
    @question.destroy
    redirect_to questions_path
  end


  private

  def question_params
    # this method will return a hash like this:
    # { title: "whatever title", author: "some person", body: "blah blah blah" }
    params.require(:question).permit(:title, :description)

  end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = env['omniauth.auth']
    user = User.find_or_create_from_omniauth(auth)
    set_current_user(user)
    flash[:notice] = "You're now signed in as #{user.username}!"

    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out."
    redirect_to '/questions'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<%= form_for [@question,@answer] do |f| %>

  <%= f.label :description %>:
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag("vendor/assets/stylesheets/styles.css") %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "header">
  <%= link_to "Questions", questions_path %>
<div class = "link">
  <% if signed_in? %>
  <%= link_to "Sign Out", session_path(current_user), method: :delete %>
  <% else %>
  <%= link_to "Sign In", "/auth/github" %>
  <% end %>
</div>
</div>

<% if flash.any? %>
<div id = "flash"><%= flash[:notice] %></div>
<% end %>

<div id = "ask">
  <%= link_to "Ask", new_question_path %>
</div>


<div id = "body">

<%= yield %>

</div>

</body>
</html>

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title, size: 85 %>

  <span id = "delete"><%= link_to "Delete", question_path(@question), method: :delete %></span>
  <br>



  <%= f.label :description %>:
  <%= f.text_area :description, :rows => 10, :cols => 80  %><br>

  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<ul id = "question_list">
<% @questions.each do |q| %>
<li><%= link_to q.title, question_path(q) %></li>
<% end %>
</ul>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title, size: 120 %><br>

  <%= f.label :description %>:
  <%= f.text_area :description, :rows => 10, :cols => 85 %><br>

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<br>
<div class = "title">
  <%= @question.title %>


  <% if signed_in? && @creator == current_user.id %>
  <div id = "edit_options">
    <ul>
    <li><%= link_to "Update", edit_question_path %></li>
    <li><%= link_to "Delete", question_path(@question), method: :delete %></li>
    </ul>

  </div>
  <% end %>

</div>

<div class = "description"><%= @question.description %></div>


<div class = "title" style = "background:#FF6F00">Answers</div>

<ul id = "answers">
<% @answers.each do |a| %>
  <li>
    <b><%= "[Favorite]" if a.is_favorite == true %></b>
    <%= a.description %>
    <% if signed_in? && @creator == current_user.id && a.is_favorite != true %>
      <%= link_to "Make Favorite", question_answer_path(@question, a),method: :patch %>
    <% end %>
  </li>
<% end %>
</ul>

<div id = "submit_answer">
  <%= form_for [@question,@new_answer] do |f| %>

    <%= f.label "Add your answer" %>:
    <%= f.text_area :description,:rows => 10, :cols => 85 %><br>

    <%= f.submit %>
  <% end %>
</div>